export function getAdminCopy(language: "MN" | "EN") {
  return language === "MN"
    ? {
        dashboard: "Dashboard",
        website: "Website",
        categoriesMenu: "Ангилал",
        productsMenu: "Бүтээгдэхүүн",
        messagesMenu: "Мессеж",
        ordersMenu: "Захиалга",
        usersMenu: "Хэрэглэгч",
        analyticsMenu: "Аналитик",
        dashboardTitle: "Админ хянах самбар",
        dashboardText: "Website, Ангилал, Бүтээгдэхүүн хэсгүүдийг modal-based workflow-оор удирдана.",
        websiteTitle: "Вэб контент",
        websiteText: "Storefront settings, market, testimonial мэдээллүүд энэ хэсгээс modal-аар засагдана.",
        categoriesTitle: "Ангиллын удирдлага",
        categoriesText: "Ангилал нэмэх, засах, идэвхжүүлэх, идэвхгүй болгох бүх үйлдэл modal-оор хийгдэнэ.",
        productsTitle: "Бүтээгдэхүүний удирдлага",
        productsText: "Бүх бүтээгдэхүүний статус, үнэ, ангилал, тайлбар, variant-ийг modal-аар удирдана.",
        searchByName: "Нэрээр хайх...",
        allCategories: "Бүх ангилал",
        priceMin: "Үнэ (мин)",
        priceMax: "Үнэ (макс)",
        clearFilters: "Цэвэрлэх",
        showingResults: "үр дүн",
        messagesTitle: "Ирсэн мессежүүд",
        messagesText: "Contact page-ийн form-оор илгээсэн мессежүүдийг эндээс харна.",
        ordersTitle: "Захиалгын удирдлага",
        ordersText: "Захиалгын төлөв, төлбөр, хүргэлтийн явц болон хүлээн авагчийн мэдээллийг эндээс удирдана.",
        newOrders: "Шинэ",
        deliveringOrders: "Хүргэлтэнд гарсан",
        deliveredOrders: "Хүргэгдсэн",
        paymentLabel: "Төлбөр",
        createdLabel: "Үүссэн огноо",
        editOrder: "Захиалга засах",
        orderDetailsTitle: "Захиалгын мэдээлэл засах",
        orderDetailsText: "Төлөв, хүлээн авагчийн мэдээлэл, хүргэлтийн хаягийг админаас шинэчилнэ.",
        orderInfo: "Захиалгын ерөнхий мэдээлэл",
        orderItemsLabel: "Захиалсан бараа",
        orderPaymentLabel: "Төлбөрийн төлөв",
        paymentStateLabel: "Төлбөрийн төлөв",
        paidAtLabel: "Төлбөр төлөгдсөн огноо",
        orderStatusHelp: "Төлөв өөрчлөхөд payment state автоматаар уялдан шинэчлэгдэнэ.",
        orderReadonlyItemsNote: "Барааны мөрүүдийг энэ хувилбарт зөвхөн харах боломжтой.",
        orderUpdateFailed: "Захиалгын мэдээллийг хадгалж чадсангүй.",
        products: "Бүтээгдэхүүн",
        collections: "Ангилал",
        orders: "Захиалга",
        banners: "Баннер",
        navigation: "Header navigation",
        markets: "Markets",
        journal: "Сэтгүүл",
        testimonials: "Testimonials",
        settings: "Website Settings",
        totalProducts: "Бүтээгдэхүүн",
        totalCollections: "Ангилал",
        totalMessages: "Мессеж",
        totalOrders: "Захиалга",
        totalBanners: "Баннер",
        totalMarkets: "Markets",
        totalTestimonials: "Testimonials",
        activeCount: "Active",
        inactiveCount: "Inactive",
        actions: "Action",
        linkedProducts: "Хамааралтай бүтээгдэхүүн",
        pendingOrders: "Хүлээгдэж буй",
        paidOrders: "Төлбөр төлөгдсөн",
        guestOrders: "Зочин захиалга",
        bestSellerCount: "Best seller",
        compareShort: "Compare",
        image: "Зураг",
        emptyCategories: "Ангилал байхгүй байна.",
        emptyProducts: "Бүтээгдэхүүн байхгүй байна.",
        emptyMessages: "Одоогоор мессеж ирээгүй байна.",
        emptyOrders: "Захиалга байхгүй байна.",
        openWebsite: "Website",
        openCategories: "Ангилал",
        openProducts: "Бүтээгдэхүүн",
        openOrders: "Захиалга",
        openUsers: "Хэрэглэгч",
        signedIn: "Нэвтэрсэн хэрэглэгч",
        status: "Төлөв",
        active: "Active",
        inactive: "Inactive",
        live: "Active session",
        logout: "Гарах",
        add: "Нэмэх",
        edit: "Засах",
        delete: "Устгах",
        cancel: "Болих",
        save: "Хадгалах",
        close: "Хаах",
        createCollection: "Ангилал нэмэх",
        createProduct: "Бүтээгдэхүүн нэмэх",
        createBanner: "Баннер нэмэх",
        editNavigation: "Header navigation засах",
        editJournalSection: "Journal хэсэг засах",
        createJournal: "Journal нийтлэл нэмэх",
        editJournal: "Journal нийтлэл засах",
        createJournalEntry: "Нийтлэл нэмэх",
        createMarket: "Market нэмэх",
        createTestimonial: "Testimonial нэмэх",
        editWebsite: "Website тохиргоо засах",
        reset: "Анхны төлөвт оруулах",
        resetConfirmTitle: "Storefront reset",
        resetConfirmDescription: "Бүх storefront мэдээллийг default утга руу буцаах уу?",
        basicInfo: "Ерөнхий мэдээлэл",
        productEditor: "Product details",
        dangerReset: "Shop-ийн бүх засварыг default утга руу буцаах уу?",
        bestSeller: "Best seller",
        comparePrice: "Compare at price",
        badge: "Badge",
        variants: "Variants",
        variantName: "Хэмжээ",
        variantPrice: "Үнэ",
        addVariant: "Variant нэмэх",
        soldCount: "Зарагдсан",
        stockRemaining: "Үлдэгдэл",
        imageHelp: "Category card болон home section дээр харагдах зургийн URL оруулна.",
        imagePreview: "Зургийн preview",
        variantsHelp: "Нэг мөрөнд `Нэр|Үнэ` форматаар оруулна.",
        productImages: "Бүтээгдэхүүний зураг",
        productImagesHelp: "Ихдээ 3 зураг upload хийж болно.",
        addImage: "Зураг нэмэх",
        ingredientsLabel: "Орц найрлага",
        addIngredient: "Орц нэмэх",
        ingredientPlaceholder: "Орцын нэр",
        usageLabel: "Үйлчилгээ",
        howToUseLabel: "Хэрэглэх заавар",
        cautionLabel: "Анхаар зүйлс",
        shelfLifeLabel: "Хадгалах хугацаа",
        sizeLabelField: "Хэмжээ / Грамм",
        sizeLabelHelp: "Variants байхгүй үед харагдана. Жишээ: 85 гр, 100 мл",
        description: "Тайлбар",
        price: "Үнэ",
        costPrice: "Өртөг",
        costPriceHelp: "Нэгж бүтээгдэхүүний өөрийн өртөг. Борлуулсан барааны өртгийн бичилтэд хэрэглэгдэнэ. Үйлдвэрлэлийн багц дуусахад автоматаар шинэчлэгдэнэ.",
        wholesalePrice: "Бөөний үнэ",
        wholesalePriceHelp: "Бөөний харилцагчид тавих үнэ. 0 бол жирийн үнийг хэрэглэнэ.",
        minStockLevel: "Нөөцийн доод хязгаар",
        name: "Нэр",
        category: "Ангилал",
        brandName: "Brand нэр",
        brandDescription: "Brand description",
        labelMn: "Монгол гарчиг",
        labelEn: "English label",
        pageBanner: "Page banner",
        pageBannerHelp: "Тухайн menu route-ийн hero background дээр харагдах зургийн URL.",
        group: "Байршил",
        customerInfo: "Хүлээн авагчийн мэдээлэл",
        addressInfo: "Хүргэлтийн хаяг",
        note: "Тэмдэглэл",
        receivedAt: "Ирсэн хугацаа",
        senderName: "Илгээгч",
        senderEmail: "И-мэйл",
        messageSubject: "Сэдэв",
        messageBody: "Мессеж",
        heroHeading: "Hero heading",
        heroSubtext: "Hero subtext",
        aboutTitle: "About title",
        aboutBody: "About body",
        contactPhone: "Утасны дугаар",
        contactEmail: "Contact email",
        location: "Байршил",
        responseTime: "Response time",
        shippingFee: "Хүргэлтийн төлбөр (₮)",
        freeShippingThreshold: "Үнэгүй хүргэлтийн доод дүн (₮)",
        minOrderForDelivery: "Хүргэлт хийх доод дүн (₮)",
        facebookUrl: "Facebook URL",
        instagramHandle: "Instagram handle",
        instagramUrl: "Instagram URL",
        mapNote: "Map note",
        marketIntro: "Market intro",
        storeHoursText: "Store hours text",
        wholesaleHeading: "Wholesale heading",
        wholesaleText: "Wholesale text",
        wholesaleEmail: "Wholesale email",
        leftGroup: "Зүүн тал",
        rightGroup: "Баруун тал",
        sortOrder: "Дараалал",
        journalHeadingMn: "Journal гарчиг (MN)",
        journalHeadingEn: "Journal heading (EN)",
        journalSubtextMn: "Journal тайлбар (MN)",
        journalSubtextEn: "Journal subtext (EN)",
        journalEntries: "Journal нийтлэлүүд",
        publishedAt: "Нийтэлсэн огноо",
        categoryMn: "Ангилал (MN)",
        categoryEn: "Category (EN)",
        titleMn: "Гарчиг (MN)",
        titleEn: "Title (EN)",
        excerptMn: "Товч агуулга (MN)",
        excerptEn: "Excerpt (EN)",
        journalImage: "Journal зураг",
        journalImageHelp: "Blog card дээр харагдах cover image URL. URL оруулах эсвэл шууд файл upload хийж болно.",
        schedule: "Хуваарь",
        address: "Хаяг",
        season: "Улирал",
        quote: "Сэтгэгдэл",
        author: "Зохиогч",
        displayName: "Дэлгэцийн нэр",
        userRole: "Хэрэглэгчийн эрх",
        userUid: "UID",
        userProviders: "Provider-ууд",
        registeredVia: "Бүртгэсэн төрөл",
        lastAuth: "Сүүлийн нэвтрэлт",
        registeredAt: "Бүртгүүлсэн огноо",
        phoneLoginEmail: "Phone login email",
        editUser: "Хэрэглэгч засах",
        userModalTitle: "Хэрэглэгчийн мэдээлэл",
        userModalDescription: "Sysadmin болон admin эрхтэй хэрэглэгч бусад хэрэглэгчийн мэдээлэл, эрхийг эндээс шинэчилнэ.",
        userUpdateFailed: "Хэрэглэгчийн мэдээллийг хадгалж чадсангүй.",
        currentUserReadOnly: "Өөрийн профайлыг энэ хэсгээс засахгүй.",
        bannerCollection: "Ангилал",
        bannerImage: "Баннер зураг",
        bannerUpload: "Зураг upload",
        bannerUploadProgress: "Зураг upload хийж байна...",
        bannerUploadFailed: "Зураг upload амжилтгүй боллоо.",
        bannerSummary: "Home hero slideshow дээрх баннерууд.",
        messagesLast7Days: "Сүүлийн 7 хоног",
        latestReceived: "Сүүлд ирсэн",
        messagesListHelp: "Contact form-оос ирсэн мессежүүд newest эхэндээ харагдана.",
        bannerModalCreate: "Баннер нэмэх",
        bannerModalEdit: "Баннер засах",
        deleteBannerDescription: "Энэ баннерыг устгах уу?",
        bannerDependencyError: "Энэ ангилал баннер дээр ашиглагдаж байгаа тул устгах боломжгүй.",
        bannerImageHelp: "URL оруулах эсвэл шууд файл upload хийж болно.",
        bannerAspectTitle: "Зөвлөмжит зургийн стандарт",
        bannerAspectValue: "16:9 харьцаа",
        bannerAspectHelp: "Хамгийн багадаа 1600 x 900, боломжтой бол 1920 x 1080 зураг ашиглаарай.",
        bannerImportedSource: "Эх сурвалж: SAVANA",
        bannerUploadedSource: "Эх сурвалж: Admin upload",
        quickOverview: "Хурдан тойм",
        livePreview: "Storefront live data",
        language: "Хэл",
        english: "English",
        mongolian: "Монгол",
        firebaseSync: "Firebase sync",
        firestoreStructure: "Firestore бүтэц",
        syncLoading: "Уншиж байна",
        syncSaving: "Хадгалж байна",
        syncLive: "Live",
        syncError: "Алдаа",
        settingsModalTitle: "Website settings",
        settingsModalText: "Brand болон website дээр харагдах үндсэн текстүүдийг нэг modal-аас шинэчилнэ.",
        collectionModalCreate: "Ангилал нэмэх",
        collectionModalEdit: "Ангилал засах",
        categoryLevel: "Түвшин",
        categoryLevelGroup: "Бүлэг",
        categoryLevelCategory: "Ангилал",
        categoryLevelType: "Төрөл",
        categoryParent: "Эцэг ангилал",
        categoryParentNone: "Эцэг ангилал сонгоно уу",
        categoryCode: "Дугаарлалт",
        categoryGroupName: "Бүлэг нэр",
        categoryCategoryName: "Ангилал нэр",
        categoryTypeName: "Төрөл нэр",
        addGroup: "Бүлэг нэмэх",
        addCategoryChild: "Ангилал нэмэх",
        addTypeChild: "Төрөл нэмэх",
        categoryParentLabel: "Эцэг:",
        productModalCreate: "Бүтээгдэхүүн нэмэх",
        productModalEdit: "Бүтээгдэхүүн засах",
        marketModalCreate: "Market нэмэх",
        marketModalEdit: "Market засах",
        testimonialModalCreate: "Testimonial нэмэх",
        testimonialModalEdit: "Testimonial засах",
        confirmDeleteTitle: "Устгах баталгаажуулалт",
        deleteProductDescription: "Энэ бүтээгдэхүүнийг устгах уу?",
        productDeleteLinkedError: "Энэ бүтээгдэхүүнд холбоотой борлуулалт эсвэл шилжүүлэг бүртгэгдсэн тул устгах боломжгүй.",
        deleteNavigationDescription: "Энэ navigation item-ийг header-ээс нуух уу?",
        navigationModalCreate: "Navigation item идэвхжүүлэх",
        navigationModalEdit: "Navigation item засах",
        journalSettingsModalTitle: "Journal хэсгийн тохиргоо",
        journalModalCreate: "Journal нийтлэл нэмэх",
        journalModalEdit: "Journal нийтлэл засах",
        deleteJournalEntryDescription: "Энэ journal нийтлэлийг устгах уу?",
        deleteMarketDescription: "Энэ market мэдээллийг устгах уу?",
        deleteTestimonialDescription: "Энэ testimonial-ийг устгах уу?",
        deleteCollectionDescription: "Энэ ангиллыг устгах уу?",
        categoryDeleteLocked: "Энэ ангиллыг устгах боломжгүй.",
        categoryLastLocked: "Сүүлийн үлдсэн ангиллыг устгах боломжгүй. Эхлээд өөр ангилал үүсгэнэ үү.",
        categoryDependencyError: "Энэ ангилал дээр хамааралтай бүтээгдэхүүнүүд байгаа тул устгах боломжгүй.",
        noCategories: "Идэвхтэй ангилал байхгүй байна. Эхлээд ангилал идэвхжүүлнэ үү.",
        categorySystemNote: "Системийн ангилал",
        currentStatus: "Одоогийн төлөв",
        activeOnWebsite: "Active үед вэб дээр харагдана.",
        settingsInactiveNote: "Website settings inactive үед public site default контентийг ашиглана.",
        systemProtected: "System protected",
        navigationSummary: "Header menu дээр харагдах page-үүдийн дараалал, хэл, статус.",
        messagesSummary: "Contact page-ээс илгээсэн хэрэглэгчийн хүсэлтүүд.",
        journalSummary: "Сэтгүүл page дээрх гарчиг, тайлбар, нийтлэлүүд.",
        marketSummary: "Find Us page дээрх мэдээлэл.",
        testimonialSummary: "Home page дээрх customer review.",
        categorySummary: "Header, filter, storefront cards дээр ашиглагдана.",
        featuredProduct: "Онцлох бүтээгдэхүүн",
        featuredProductHelp: "Нүүр хуудсанд онцлох бүтээгдэхүүний орц найрлагыг харуулна.",
        featuredProductNone: "Автомат (эхний бүтээгдэхүүн)",
        productSummary: "Collections page, home page, detail page дээр ашиглагдана.",
        statusSummary: "Status active үед selection болон public web дээр харагдана.",
        inventoryTitle: "Нөөц ба агуулах",
        inventoryText: "Сав, баглаа боодол болон түүхий эдийн нөөцийг удирдана.",
        packagingTitle: "Нөөц ба агуулах",
        packagingName: "Нэр",
        packagingSize: "Хэмжээ",
        packagingRemaining: "Үлдэгдэл",
        packagingModalCreate: "Нөөц нэмэх",
        packagingModalEdit: "Сав засах",
        deletePackagingDescription: "Энэ савыг устгах уу?",
        packagingEmpty: "Бүртгэгдсэн сав байхгүй байна.",
        packagingSummary: "Үйлдвэрлэлд хэрэглэгдэх сав, баглаа боодлын бүртгэл.",
        packagingUnitCost: "Нэгжийн үнэ",
        packagingPurchasesTitle: "Татан авалт",
        packagingPurchasesEmpty: "Татан авалтын бүртгэл байхгүй.",
        packagingPurchaseAdd: "Татан авалт бүртгэх",
        packagingPurchaseModalTitle: "Татан авалт бүртгэх",
        packagingPurchaseTotalAdded: "Нийт нэмэгдсэн",
        packagingPurchaseTotalAmount: "Нийт дүн",
        packagingPurchaseDeleteConfirm: "Энэ татан авалтын бүртгэлийг устгахад нөөц буцаан хасагдана. Үргэлжлүүлэх үү?",
        packagingUsageTitle: "Гар зарцуулалт",
        packagingUsageEmpty: "Гар зарцуулалтын бүртгэл байхгүй.",
        packagingUsageAdd: "Зарцуулалт бүртгэх",
        packagingUsageModalTitle: "Зарцуулалт бүртгэх",
        packagingUsageTotal: "Нийт зарцуулсан",
        packagingUsageDeleteConfirm: "Энэ зарцуулалтын бүртгэлийг устгахад нөөц буцаан нэмэгдэнэ. Үргэлжлүүлэх үү?",
        packagingTotalCostValue: "Нийт өртөг",
        packagingTotalConsumedValue: "Зарцуулагдсан дүн",
        productionKicker: "Үйлдвэрлэл",
        productionTitle: "Үйлдвэрлэлийн удирдлага",
        productionText: "Саван үйлдвэрлэлийн batch-уудыг төлөвлөж, түүхий эдийн зарцуулалт болон бэлэн болох хугацааг хянана.",
        productionPlanningCount: "Төлөвлөж буй",
        productionInProgressCount: "Хийгдэж буй",
        productionCuringCount: "Боловсорч буй",
        productionReadyThisMonth: "Энэ сард бэлэн болсон",
        productionLowStockWarning: "Дутагдаж буй түүхий эд",
        productionBatchesTitle: "Үйлдвэрлэлийн batch",
        productionBatchesSummary: "Түүхий эд, бэлэн болох хугацаа, үр дүнг дагаж хөтөлнө.",
        productionBatchesEmpty: "Одоогоор үүсгэсэн batch байхгүй.",
        productionBatchModalCreate: "Шинэ batch",
        productionBatchModalEdit: "Batch засах",
        productionBatchCode: "Batch код",
        productionBatchProduct: "Бүтээгдэхүүн",
        productionBatchStatus: "Төлөв",
        productionBatchPlannedQty: "Төлөвлөсөн тоо",
        productionBatchActualQty: "Бодит бэлэн",
        productionBatchStartedAt: "Хийсэн огноо",
        productionBatchExpectedReadyAt: "Бэлэн болох огноо",
        productionBatchReadyAt: "Бэлэн болсон огноо",
        productionBatchSupplies: "Түүхий эд",
        productionBatchAddSupply: "Түүхий эд нэмэх",
        productionBatchNotes: "Тэмдэглэл",
        productionBatchTotalCost: "Нийт өртөг",
        productionBatchEmptySupplies: "Түүхий эдээ оруулна уу.",
        productionBatchCuringHint: "Натурал саван ихэвчлэн 4-6 долоо хоног боловсруулагдана.",
        deleteProductionBatchDescription: "Энэ batch-ийг устгах уу? Түүхий эд болон нөөц буцаагдана.",
        productionBatchVariant: "Variant",
        productionBatchRecipeApplied: "Жороор орц автоматаар тооцоологдлоо.",
        productionBatchRecipeMissing: "Энэ бүтээгдэхүүн/variant-д жор бүртгэгдээгүй тул орцыг гараар нэмнэ үү.",
        productionBatchRecipeRecalc: "Жороор дахин тооцоолох",
        recipesMenu: "Жор",
        recipesTitle: "Жорын удирдлага",
        recipesText: "Бүтээгдэхүүний ангилал, variant-д тулгуурлан үйлдвэрлэлийн орцыг бүртгэж, засаж, устгана.",
        recipesListTitle: "Бүртгэлтэй жорууд",
        recipesListSummary: "Нэг жор нь тодорхой тооны бүтээгдэхүүн үйлдвэрлэхэд шаардагдах түүхий эдийг тодорхойлно.",
        recipesEmpty: "Одоогоор бүртгэсэн жор алга.",
        recipesCount: "Нийт жор",
        recipesProductsCovered: "Жортой бүтээгдэхүүн",
        recipesProductsMissing: "Жоргүй бүтээгдэхүүн",
        recipeModalCreate: "Шинэ жор",
        recipeModalEdit: "Жор засах",
        recipeCategory: "Ангилал",
        recipeProduct: "Бүтээгдэхүүн",
        recipeVariant: "Variant",
        recipeVariantAll: "Бүх variant",
        recipeName: "Жорын нэр (заавал биш)",
        recipeNamePlaceholder: "Жишээ: Уламжлалт орц, Хямд орц гэх мэт",
        recipeUnnamed: "Нэргүй жор",
        recipeBaseQuantity: "Гарц (ширхэг)",
        recipeBaseQuantityHint: "Доорх орцоор хэдэн ширхэг бүтээгдэхүүн гарахыг оруулна уу.",
        recipeSupplies: "Орц (түүхий эд)",
        recipeAddSupply: "Орц нэмэх",
        recipeEmptySupplies: "Орцоо оруулна уу.",
        recipeNotes: "Тэмдэглэл",
        recipeTotalCost: "Нийт өртөг",
        recipeUnitCost: "1 ширхэгийн өртөг",
        recipeNoProducts: "Эхлээд бүтээгдэхүүн бүртгэнэ үү.",
        deleteRecipeDescription: "Энэ жорыг устгах уу?",
        statusPlanning: "Төлөвлөж буй",
        statusInProgress: "Хийгдэж буй",
        statusCuring: "Боловсорч буй",
        statusReady: "Бэлэн",
        productionAdvanceTitle: "Төлөв шинэчлэх",
        productionAdvanceStart: "Эхлүүлэх",
        productionAdvanceCuring: "Боловсруулалтад",
        productionAdvanceReady: "Бэлэн болгох",
        productionAdvanceConfirmStart: "Түүхий эдийг зарцуулж, үйлдвэрлэл эхлүүлэх үү?",
        productionAdvanceConfirmCuring: "Батчийг боловсруулалтын үе шат руу шилжүүлэх үү?",
        productionAdvanceConfirmReady: "Бодит бэлэн болсон тоог оруулаад нөөцөд нэмнэ үү.",
        productionAdvanceInsufficient: "Дараах түүхий эд хүрэлцэхгүй байна:",
        productionAdvanceActualQtyLabel: "Бодит бэлэн болсон тоо",
        productionAdvanceRequired: "Шаардлагатай",
        productionAdvanceAvailable: "Үлдэгдэл",
        rawMaterialsTitle: "Түүхий эдийн сан",
        rawMaterialsSummary: "Үйлдвэрлэлд хэрэглэгдэх түүхий эдийн нөөц.",
        rawMaterialsEmpty: "Бүртгэгдсэн түүхий эд байхгүй.",
        rawMaterialModalCreate: "Түүхий эд нэмэх",
        rawMaterialModalEdit: "Түүхий эд засах",
        rawMaterialName: "Нэр",
        rawMaterialCategory: "Ангилал",
        rawMaterialUnit: "Нэгж",
        rawMaterialRemaining: "Үлдэгдэл",
        rawMaterialUnitCost: "Нэгжийн өртөг",
        rawMaterialNotes: "Тэмдэглэл",
        deleteRawMaterialDescription: "Энэ түүхий эдийг устгах уу?",
        rawMaterialHistoryTitle: "Зарцуулалт",
        rawMaterialHistoryEmpty: "Энэ түүхий эдийг ашигласан үйлдвэрлэл байхгүй.",
        rawMaterialHistoryBatchCode: "Дугаар",
        rawMaterialHistoryProduct: "Бүтээгдэхүүн",
        rawMaterialHistoryStatus: "Статус",
        rawMaterialHistoryStartedAt: "Эхэлсэн огноо",
        rawMaterialHistoryQty: "Хэмжээ",
        rawMaterialHistoryDeducted: "Нийт хасагдсан",
        rawMaterialHistoryPending: "Төлөвлөгөө",
        rawMaterialPurchasesTitle: "Татан авалт",
        rawMaterialPurchasesEmpty: "Татан авалтын бүртгэл байхгүй.",
        rawMaterialPurchaseAdd: "Татан авалт бүртгэх",
        rawMaterialPurchaseModalTitle: "Татан авалт бүртгэх",
        rawMaterialPurchasedAt: "Татан авсан",
        rawMaterialPurchaseQty: "Хэмжээ",
        rawMaterialPurchaseUnitCost: "Нэгжийн үнэ",
        rawMaterialPurchasePaymentMethod: "Төлсөн данс",
        rawMaterialPurchaseSupplier: "Нийлүүлэгч",
        rawMaterialPurchaseOrigin: "Хаанаас",
        rawMaterialPurchaseCargo: "Карго зардал (₮)",
        rawMaterialPurchaseNotes: "Тэмдэглэл",
        rawMaterialPurchaseTotalAdded: "Нийт нэмэгдсэн",
        rawMaterialPurchaseTotalAmount: "Нийт дүн",
        rawMaterialPurchaseDeleteConfirm: "Энэ татан авалтын бүртгэлийг устгахад нөөц буцаан хасагдана. Үргэлжлүүлэх үү?",
        rawMaterialUsageTitle: "Гар зарцуулалт",
        rawMaterialUsageEmpty: "Гар зарцуулалтын бүртгэл байхгүй.",
        rawMaterialUsageAdd: "Зарцуулалт бүртгэх",
        rawMaterialUsageModalTitle: "Зарцуулалт бүртгэх",
        rawMaterialUsedAt: "Зарцуулсан огноо",
        rawMaterialUsageQty: "Хэмжээ",
        rawMaterialUsageReason: "Шалтгаан",
        rawMaterialUsageNotes: "Тэмдэглэл",
        rawMaterialUsageTotal: "Нийт зарцуулсан",
        rawMaterialUsageInsufficientStock: "Хангалттай нөөц алга.",
        rawMaterialUsageDeleteConfirm: "Энэ зарцуулалтын бүртгэлийг устгахад нөөц буцаан нэмэгдэнэ. Үргэлжлүүлэх үү?",
        rawMaterialTotalCostValue: "Нийт өртөг",
        rawMaterialTotalConsumedValue: "Зарцуулагдсан дүн",
        rawMaterialCategoryOil: "Тос",
        rawMaterialCategoryLye: "Шүлт",
        rawMaterialCategoryFragrance: "Үнэртэн",
        rawMaterialCategoryColorant: "Будагч",
        rawMaterialCategoryAdditive: "Нэмэлт",
        rawMaterialCategoryOther: "Бусад",
        contactsTitle: "Харилцагчийн бүртгэл",
        contactsText: "Хувь хүн, байгууллага харилцагчийн нэр, утас, хаягийг нэг бүртгэлд хөтөлнө.",
        contactsListText: "Мөр дээр дарж тухайн харилцагчийн өмнөх худалдан авалтыг харна.",
        contactPurchaseCount: "Худалдан авалт",
        contactPurchaseTotal: "Нийт зарцуулсан",
        contactLastPurchase: "Сүүлд авсан",
        contactAveragePurchase: "Дундаж дүн",
        contactNoPurchases: "Энэ харилцагчид бүртгэгдсэн худалдан авалт алга байна.",
        newContact: "Шинэ харилцагч",
        editContact: "Харилцагч засах",
        totalContacts: "Нийт харилцагч",
        contactSearchPlaceholder: "Нэр, утас, кодоор хайх...",
        contactEmpty: "Бүртгэлтэй харилцагч байхгүй байна.",
        contactNoMatch: "Хайлтад тохирох харилцагч олдсонгүй.",
        deleteContactTitle: "Харилцагч устгах",
        deleteContactDescription: "Энэ харилцагчийг устгах уу? Өмнө нь бүртгэсэн борлуулалт хэвээр үлдэнэ.",
        saleContactPicker: "Бүртгэлтэй харилцагчаас сонгох",
        saleContactPickerNote: "Заавал биш — сонгосон харилцагчийн мэдээлэл доорх талбаруудад бөглөгдөнө.",
        saleContactClear: "Сонголтыг цуцлах",
        saleContactNoMatch: "Тохирох харилцагч олдсонгүй.",
        customersTitle: "Борлуулагчийн удирдлага",
        customersText: "Байгууллага болон хувь борлуулагчдын нэр, утас, хаяг, төлвийг эндээс удирдана.",
        customerRegisteredAt: "Бүртгэсэн огноо",
        customersKicker: "CRM",
        newCustomer: "Шинэ борлуулагч",
        editCustomer: "Борлуулагч засах",
        customerTypeAll: "Бүх төрөл",
        customerTypeOrg: "Байгууллага",
        customerTypeInd: "Хувь хүн",
        customerCode: "Код",
        customerNameLabel: "Нэр",
        customerDisplayName: "Товч нэр",
        customerRegNo: "Регистр / ТТД",
        customerContactPerson: "Холбоо барих хүн",
        customerPhone: "Утас",
        customerSecondaryPhone: "Нэмэлт утас",
        customerEmail: "И-мэйл",
        customerAddress: "Хаяг",
        customerNote: "Тэмдэглэл",
        customerTotalSales: "Нийт борлуулалт",
        customerTotalPaid: "Төлөгдсөн",
        customerOutstanding: "Үлдэгдэл авлага",
        customerEmpty: "Бүртгэлтэй борлуулагч байхгүй байна.",
        totalCustomers: "Нийт борлуулагч",
        activeCustomers: "Идэвхтэй",
        totalOutstanding: "Нийт авлага",
        totalTransfers: "Нийт шилжүүлэг",
        deleteCustomerDescription: "Энэ борлуулагчийг устгах уу? Өмнөх гүйлгээ нь хэвээр үлдэнэ.",
        transactionsTitle: "Борлуулагчийн шилжүүлэг",
        transactionsText: "Бараа өгөх, борлуулах, буцаах гүйлгээг бүртгэж, бүтээгдэхүүний нөөц автоматаар шинэчилнэ.",
        newTransaction: "Шинэ шилжүүлэг",
        editTransaction: "Шилжүүлэг засах",
        txNumber: "Дугаар",
        txDate: "Огноо",
        txType: "Төрөл",
        txTypeDelivery: "Бараа өгсөн",
        txTypeSale: "Борлуулсан",
        txTypeReturn: "Буцаасан",
        txCustomer: "Борлуулагч",
        txItems: "Бараанууд",
        txAddItem: "Бараа нэмэх",
        txProduct: "Бүтээгдэхүүн",
        txVariant: "Хувилбар",
        txQuantity: "Тоо",
        txUnitPrice: "Нэгж үнэ",
        txLineTotal: "Дүн",
        txSubtotal: "Дэд дүн",
        txDiscount: "Хөнгөлөлт",
        txGrandTotal: "Нийт дүн",
        txPaidAmount: "Төлсөн дүн",
        txPaymentMethod: "Төлбөрийн арга",
        txPaymentStatus: "Төлбөрийн төлөв",
        txPaymentUnpaid: "Төлөгдөөгүй",
        txPaymentPartial: "Хэсэгчилсэн",
        txPaymentPaid: "Төлөгдсөн",
        txPaymentCash: "Бэлэн",
        txPaymentBank: "Банк",
        txPaymentQpay: "QPay",
        txPaymentOther: "Бусад",
        txNote: "Тэмдэглэл",
        txEmpty: "Гүйлгээ олдсонгүй.",
        txTodaySales: "Өнөөдрийн борлуулалт",
        txMonthSales: "Энэ сарын борлуулалт",
        txOutstanding: "Нийт авлага",
        txAllTypes: "Бүх төрөл",
        txAllCustomers: "Бүх харилцагч",
        deleteTransactionDescription: "Энэ гүйлгээг устгаснаар нөөц болон харилцагчийн үлдэгдэл буцаана. Үргэлжлүүлэх үү?",
        selectCustomerFirst: "Эхлээд харилцагч сонгоно уу.",
        addAtLeastOneItem: "Дор хаяж нэг бараа нэмнэ үү.",
        discountsMenu: "Хямдрал",
        discountsTitle: "Хямдралын удирдлага",
        discountsText: "Бүтээгдэхүүн дээр хувь эсвэл дүнгээр хямдрал тохируулж, эхлэх, дуусах хугацааг тохируулна.",
        addDiscount: "Хямдрал нэмэх",
        discountProduct: "Бүтээгдэхүүн",
        discountType: "Хямдралын төрөл",
        discountTypePercent: "Хувь (%)",
        discountTypeAmount: "Дүн (₮)",
        discountValue: "Хямдралын утга",
        discountStartAt: "Эхлэх огноо",
        discountEndAt: "Дуусах огноо",
        discountEmpty: "Хямдрал бүртгэгдээгүй байна.",
        discountModalCreate: "Хямдрал нэмэх",
        discountModalEdit: "Хямдрал засах",
        deleteDiscountDescription: "Энэ хямдралыг устгах уу?",
        discountSavings: "Хямдрал",
        discountOriginalPrice: "Үндсэн үнэ",
        discountedPrice: "Хямдарсан үнэ",
        discountPercent: "хямдрал",
      }
    : {
        dashboard: "Dashboard",
        website: "Website",
        categoriesMenu: "Categories",
        productsMenu: "Products",
        messagesMenu: "Messages",
        ordersMenu: "Orders",
        usersMenu: "Users",
        analyticsMenu: "Analytics",
        dashboardTitle: "Admin dashboard",
        dashboardText: "Manage Website, Categories, and Products through modal-based workflows.",
        websiteTitle: "Website content",
        websiteText: "Storefront settings, markets, and testimonials are managed from this section.",
        categoriesTitle: "Category management",
        categoriesText: "Create, edit, activate, or deactivate categories through modal forms.",
        productsTitle: "Product management",
        productsText: "Manage product status, pricing, category, descriptions, and variants in modal forms.",
        messagesTitle: "Incoming messages",
        messagesText: "Review messages submitted from the contact page form.",
        ordersTitle: "Order management",
        ordersText: "Manage order status, payment state, delivery progress, and recipient details from one place.",
        newOrders: "New",
        deliveringOrders: "Delivering",
        deliveredOrders: "Delivered",
        paymentLabel: "Payment",
        createdLabel: "Created",
        editOrder: "Edit order",
        orderDetailsTitle: "Edit order details",
        orderDetailsText: "Update the order status, recipient details, and delivery address from admin.",
        orderInfo: "Order information",
        orderItemsLabel: "Ordered items",
        orderPaymentLabel: "Payment details",
        paymentStateLabel: "Payment state",
        paidAtLabel: "Paid at",
        orderStatusHelp: "Changing the status automatically syncs the payment state.",
        orderReadonlyItemsNote: "Line items are read-only in this version.",
        orderUpdateFailed: "Unable to save the order details.",
        products: "Products",
        collections: "Categories",
        orders: "Orders",
        banners: "Banners",
        navigation: "Header navigation",
        markets: "Markets",
        journal: "Journal",
        testimonials: "Testimonials",
        settings: "Website Settings",
        totalProducts: "Products",
        totalCollections: "Categories",
        totalMessages: "Messages",
        totalOrders: "Orders",
        totalBanners: "Banners",
        totalMarkets: "Markets",
        totalTestimonials: "Testimonials",
        activeCount: "Active",
        inactiveCount: "Inactive",
        actions: "Action",
        linkedProducts: "Linked products",
        pendingOrders: "Pending",
        paidOrders: "Paid",
        guestOrders: "Guest orders",
        bestSellerCount: "Best sellers",
        compareShort: "Compare",
        image: "Image",
        emptyCategories: "No categories found.",
        emptyProducts: "No products found.",
        emptyMessages: "No messages have been submitted yet.",
        emptyOrders: "No orders found.",
        openWebsite: "Website",
        openCategories: "Categories",
        openProducts: "Products",
        openOrders: "Orders",
        openUsers: "Users",
        signedIn: "Signed in user",
        status: "Status",
        active: "Active",
        inactive: "Inactive",
        live: "Active session",
        logout: "Logout",
        add: "Add",
        edit: "Edit",
        delete: "Delete",
        cancel: "Cancel",
        save: "Save",
        close: "Close",
        createCollection: "Create category",
        createProduct: "Create product",
        createBanner: "Create banner",
        editNavigation: "Edit header navigation",
        editJournalSection: "Edit journal section",
        createJournal: "Create journal entry",
        editJournal: "Edit journal entry",
        createJournalEntry: "Create journal entry",
        createMarket: "Create market",
        createTestimonial: "Create testimonial",
        editWebsite: "Edit website settings",
        reset: "Reset storefront",
        resetConfirmTitle: "Storefront reset",
        resetConfirmDescription: "Reset all storefront content back to defaults?",
        basicInfo: "Basic Info",
        productEditor: "Product details",
        dangerReset: "Reset all storefront edits back to defaults?",
        bestSeller: "Best seller",
        comparePrice: "Compare at price",
        badge: "Badge",
        variants: "Variants",
        variantName: "Size",
        variantPrice: "Price",
        addVariant: "Add variant",
        soldCount: "Sold",
        stockRemaining: "Remaining",
        imageHelp: "Paste the image URL used on category cards and home sections.",
        imagePreview: "Image preview",
        variantsHelp: "Enter one variant per line using `Name|Price`.",
        productImages: "Product images",
        productImagesHelp: "Upload up to 3 images.",
        addImage: "Add image",
        ingredientsLabel: "Ingredients",
        addIngredient: "Add ingredient",
        ingredientPlaceholder: "Ingredient name",
        usageLabel: "Usage",
        howToUseLabel: "How to use",
        cautionLabel: "Caution",
        shelfLifeLabel: "Shelf life",
        sizeLabelField: "Size / Weight",
        sizeLabelHelp: "Shown when no variants exist. e.g. 85g, 100ml",
        description: "Description",
        price: "Price",
        costPrice: "Cost",
        costPriceHelp: "Unit cost of the finished good. Drives the cost-of-goods-sold journal line and is refreshed automatically when a production batch completes.",
        wholesalePrice: "Wholesale price",
        wholesalePriceHelp: "Price charged to wholesale customers. Leave 0 to use the regular price.",
        minStockLevel: "Low-stock threshold",
        name: "Name",
        category: "Category",
        brandName: "Brand name",
        brandDescription: "Brand description",
        labelMn: "Mongolian label",
        labelEn: "English label",
        pageBanner: "Page banner",
        pageBannerHelp: "Image URL used as the hero background for that menu page.",
        group: "Placement",
        customerInfo: "Recipient details",
        addressInfo: "Delivery address",
        note: "Note",
        receivedAt: "Received",
        senderName: "Sender",
        senderEmail: "Email",
        messageSubject: "Subject",
        messageBody: "Message",
        heroHeading: "Hero heading",
        heroSubtext: "Hero subtext",
        aboutTitle: "About title",
        aboutBody: "About body",
        contactPhone: "Phone number",
        contactEmail: "Contact email",
        location: "Location",
        responseTime: "Response time",
        shippingFee: "Delivery fee (₮)",
        freeShippingThreshold: "Free delivery from (₮)",
        minOrderForDelivery: "Minimum order for delivery (₮)",
        facebookUrl: "Facebook URL",
        instagramHandle: "Instagram handle",
        instagramUrl: "Instagram URL",
        mapNote: "Map note",
        marketIntro: "Market intro",
        storeHoursText: "Store hours text",
        wholesaleHeading: "Wholesale heading",
        wholesaleText: "Wholesale text",
        wholesaleEmail: "Wholesale email",
        leftGroup: "Left side",
        rightGroup: "Right side",
        sortOrder: "Sort order",
        journalHeadingMn: "Journal heading (MN)",
        journalHeadingEn: "Journal heading (EN)",
        journalSubtextMn: "Journal subtext (MN)",
        journalSubtextEn: "Journal subtext (EN)",
        journalEntries: "Journal entries",
        publishedAt: "Published date",
        categoryMn: "Category (MN)",
        categoryEn: "Category (EN)",
        titleMn: "Title (MN)",
        titleEn: "Title (EN)",
        excerptMn: "Excerpt (MN)",
        excerptEn: "Excerpt (EN)",
        journalImage: "Journal image",
        journalImageHelp: "Optional cover image URL shown on the journal card. Paste a URL or upload a file directly.",
        schedule: "Schedule",
        address: "Address",
        season: "Season",
        quote: "Quote",
        author: "Author",
        displayName: "Display name",
        userRole: "User role",
        userUid: "UID",
        userProviders: "Providers",
        registeredVia: "Registered via",
        lastAuth: "Last auth",
        registeredAt: "Registered at",
        phoneLoginEmail: "Phone login email",
        editUser: "Edit user",
        userModalTitle: "User profile",
        userModalDescription: "Privileged users can review and update another user's profile and access level here.",
        userUpdateFailed: "Unable to save the user profile.",
        currentUserReadOnly: "Your own profile is not edited from this directory.",
        bannerCollection: "Categories",
        bannerImage: "Banner image",
        bannerUpload: "Upload image",
        bannerUploadProgress: "Uploading image...",
        bannerUploadFailed: "Image upload failed.",
        bannerSummary: "Displayed inside the homepage hero slideshow.",
        messagesLast7Days: "Last 7 days",
        latestReceived: "Latest",
        messagesListHelp: "Messages submitted from the contact form appear here with the newest first.",
        bannerModalCreate: "Create banner",
        bannerModalEdit: "Edit banner",
        deleteBannerDescription: "Delete this banner?",
        bannerDependencyError: "This category is used by hero banners and cannot be deleted.",
        bannerImageHelp: "Paste an image URL or upload a file directly.",
        bannerAspectTitle: "Recommended image format",
        bannerAspectValue: "16:9 aspect ratio",
        bannerAspectHelp: "Use at least 1600 x 900, ideally 1920 x 1080 for the homepage hero.",
        bannerImportedSource: "Source: SAVANA",
        bannerUploadedSource: "Source: Admin upload",
        quickOverview: "Quick overview",
        livePreview: "Storefront live data",
        language: "Language",
        english: "English",
        mongolian: "Mongolian",
        firebaseSync: "Firebase sync",
        firestoreStructure: "Firestore structure",
        syncLoading: "Loading",
        syncSaving: "Saving",
        syncLive: "Live",
        syncError: "Error",
        settingsModalTitle: "Website settings",
        settingsModalText: "Update brand and website-facing copy from one modal.",
        collectionModalCreate: "Create category",
        collectionModalEdit: "Edit category",
        categoryLevel: "Level",
        categoryLevelGroup: "Бүлэг (Group)",
        categoryLevelCategory: "Ангилал (Category)",
        categoryLevelType: "Төрөл (Type)",
        categoryParent: "Parent category",
        categoryParentNone: "Select parent category",
        categoryCode: "Code",
        categoryGroupName: "Group name (Бүлэг)",
        categoryCategoryName: "Category name (Ангилал)",
        categoryTypeName: "Type name (Төрөл)",
        addGroup: "Add group",
        addCategoryChild: "Add category",
        addTypeChild: "Add type",
        categoryParentLabel: "Parent:",
        productModalCreate: "Create product",
        productModalEdit: "Edit product",
        marketModalCreate: "Create market",
        marketModalEdit: "Edit market",
        testimonialModalCreate: "Create testimonial",
        testimonialModalEdit: "Edit testimonial",
        confirmDeleteTitle: "Delete confirmation",
        deleteProductDescription: "Delete this product?",
        productDeleteLinkedError: "This product cannot be deleted because it has linked sales or transfer records.",
        deleteNavigationDescription: "Hide this navigation item from the header?",
        navigationModalCreate: "Activate navigation item",
        navigationModalEdit: "Edit navigation item",
        journalSettingsModalTitle: "Journal section settings",
        journalModalCreate: "Create journal entry",
        journalModalEdit: "Edit journal entry",
        deleteJournalEntryDescription: "Delete this journal entry?",
        deleteMarketDescription: "Delete this market entry?",
        deleteTestimonialDescription: "Delete this testimonial?",
        deleteCollectionDescription: "Delete this category?",
        categoryDeleteLocked: "This category cannot be deleted.",
        categoryLastLocked: "This is the last remaining category. Create another one before deleting it.",
        categoryDependencyError: "This category is referenced by products and cannot be deleted.",
        noCategories: "No active categories available. Activate or create a category first.",
        categorySystemNote: "System category",
        currentStatus: "Current status",
        activeOnWebsite: "Visible on selections and website when active.",
        settingsInactiveNote: "When website settings are inactive, the public site falls back to default copy.",
        systemProtected: "System protected",
        navigationSummary: "Controls the page labels, placement, and visibility in the header menu.",
        messagesSummary: "Customer inquiries submitted from the contact page.",
        journalSummary: "Controls the journal page heading, subtext, and editorial entries.",
        marketSummary: "Displayed on the Find Us page.",
        testimonialSummary: "Displayed on the homepage.",
        categorySummary: "Used in header navigation, filters, and storefront cards.",
        featuredProduct: "Featured product",
        featuredProductHelp: "Displays the featured product's ingredients on the homepage.",
        featuredProductNone: "Auto (first product)",
        productSummary: "Used across collections, homepage, and product detail pages.",
        statusSummary: "Only active items appear in selections and on the public website.",
        searchByName: "Search by name...",
        allCategories: "All categories",
        priceMin: "Price (min)",
        priceMax: "Price (max)",
        clearFilters: "Clear",
        showingResults: "results",
        inventoryTitle: "Inventory & warehouse",
        inventoryText: "Manage packaging, raw materials, and finished goods inventory.",
        packagingTitle: "Packaging",
        packagingName: "Name",
        packagingSize: "Size",
        packagingRemaining: "Remaining",
        packagingModalCreate: "Add packaging",
        packagingModalEdit: "Edit packaging",
        deletePackagingDescription: "Delete this packaging item?",
        packagingEmpty: "No packaging items registered.",
        packagingSummary: "Packaging materials used in production.",
        packagingUnitCost: "Unit cost",
        packagingPurchasesTitle: "Purchases",
        packagingPurchasesEmpty: "No purchases recorded.",
        packagingPurchaseAdd: "Record purchase",
        packagingPurchaseModalTitle: "Record purchase",
        packagingPurchaseTotalAdded: "Total added",
        packagingPurchaseTotalAmount: "Total amount",
        packagingPurchaseDeleteConfirm: "Deleting this purchase will subtract the quantity from stock. Continue?",
        packagingUsageTitle: "Manual usage",
        packagingUsageEmpty: "No manual usage recorded.",
        packagingUsageAdd: "Record usage",
        packagingUsageModalTitle: "Record usage",
        packagingUsageTotal: "Total used",
        packagingUsageDeleteConfirm: "Deleting this usage entry will add the quantity back to stock. Continue?",
        packagingTotalCostValue: "Total cost",
        packagingTotalConsumedValue: "Total consumed",
        productionKicker: "Production",
        productionTitle: "Production management",
        productionText: "Plan soap production batches, track raw-material usage, and finished quantity.",
        productionPlanningCount: "Planning",
        productionInProgressCount: "In progress",
        productionCuringCount: "Curing",
        productionReadyThisMonth: "Ready this month",
        productionLowStockWarning: "Low raw materials",
        productionBatchesTitle: "Production batches",
        productionBatchesSummary: "Track supplies, curing time and final output.",
        productionBatchesEmpty: "No production batches yet.",
        productionBatchModalCreate: "New batch",
        productionBatchModalEdit: "Edit batch",
        productionBatchCode: "Batch code",
        productionBatchProduct: "Product",
        productionBatchStatus: "Status",
        productionBatchPlannedQty: "Planned qty",
        productionBatchActualQty: "Actual qty",
        productionBatchStartedAt: "Started at",
        productionBatchExpectedReadyAt: "Expected ready",
        productionBatchReadyAt: "Ready at",
        productionBatchSupplies: "Supplies",
        productionBatchAddSupply: "Add supply",
        productionBatchNotes: "Notes",
        productionBatchTotalCost: "Total cost",
        productionBatchEmptySupplies: "Add at least one supply.",
        productionBatchCuringHint: "Natural soap typically cures for 4-6 weeks.",
        deleteProductionBatchDescription: "Delete this batch? Stock effects will be reversed.",
        productionBatchVariant: "Variant",
        productionBatchRecipeApplied: "Supplies were calculated from the recipe.",
        productionBatchRecipeMissing: "No recipe for this product/variant — add supplies manually.",
        productionBatchRecipeRecalc: "Recalculate from recipe",
        recipesMenu: "Recipes",
        recipesTitle: "Recipe management",
        recipesText: "Register, edit, and delete production recipes per product category and variant.",
        recipesListTitle: "Registered recipes",
        recipesListSummary: "A recipe defines the raw materials needed to produce a given number of units.",
        recipesEmpty: "No recipes registered yet.",
        recipesCount: "Total recipes",
        recipesProductsCovered: "Products with a recipe",
        recipesProductsMissing: "Products without a recipe",
        recipeModalCreate: "New recipe",
        recipeModalEdit: "Edit recipe",
        recipeCategory: "Category",
        recipeProduct: "Product",
        recipeVariant: "Variant",
        recipeVariantAll: "All variants",
        recipeName: "Recipe name (optional)",
        recipeNamePlaceholder: "e.g. Classic recipe, Budget recipe",
        recipeUnnamed: "Unnamed recipe",
        recipeBaseQuantity: "Yield (units)",
        recipeBaseQuantityHint: "How many finished units the supplies below produce.",
        recipeSupplies: "Supplies",
        recipeAddSupply: "Add supply",
        recipeEmptySupplies: "Add at least one supply.",
        recipeNotes: "Notes",
        recipeTotalCost: "Total cost",
        recipeUnitCost: "Cost per unit",
        recipeNoProducts: "Register a product first.",
        deleteRecipeDescription: "Delete this recipe?",
        statusPlanning: "Planning",
        statusInProgress: "In progress",
        statusCuring: "Curing",
        statusReady: "Ready",
        productionAdvanceTitle: "Advance status",
        productionAdvanceStart: "Start",
        productionAdvanceCuring: "Move to curing",
        productionAdvanceReady: "Mark ready",
        productionAdvanceConfirmStart: "Deduct supplies and start production?",
        productionAdvanceConfirmCuring: "Move this batch into the curing stage?",
        productionAdvanceConfirmReady: "Enter the final quantity produced. It will be added to product stock.",
        productionAdvanceInsufficient: "Insufficient raw materials:",
        productionAdvanceActualQtyLabel: "Actual quantity produced",
        productionAdvanceRequired: "Required",
        productionAdvanceAvailable: "Available",
        rawMaterialsTitle: "Raw materials",
        rawMaterialsSummary: "Master list of soap-making raw materials.",
        rawMaterialsEmpty: "No raw materials yet.",
        rawMaterialModalCreate: "Add raw material",
        rawMaterialModalEdit: "Edit raw material",
        rawMaterialName: "Name",
        rawMaterialCategory: "Category",
        rawMaterialUnit: "Unit",
        rawMaterialRemaining: "Remaining",
        rawMaterialUnitCost: "Unit cost",
        rawMaterialNotes: "Notes",
        deleteRawMaterialDescription: "Delete this raw material?",
        rawMaterialHistoryTitle: "Production usage",
        rawMaterialHistoryEmpty: "No production batches have used this material.",
        rawMaterialHistoryBatchCode: "Batch code",
        rawMaterialHistoryProduct: "Product",
        rawMaterialHistoryStatus: "Status",
        rawMaterialHistoryStartedAt: "Started",
        rawMaterialHistoryQty: "Quantity",
        rawMaterialHistoryDeducted: "Total deducted",
        rawMaterialHistoryPending: "Planned",
        rawMaterialPurchasesTitle: "Purchases",
        rawMaterialPurchasesEmpty: "No purchases recorded.",
        rawMaterialPurchaseAdd: "Record purchase",
        rawMaterialPurchaseModalTitle: "Record purchase",
        rawMaterialPurchasedAt: "Purchase date",
        rawMaterialPurchaseQty: "Quantity",
        rawMaterialPurchaseUnitCost: "Unit cost",
        rawMaterialPurchasePaymentMethod: "Paid from",
        rawMaterialPurchaseSupplier: "Supplier",
        rawMaterialPurchaseOrigin: "Origin",
        rawMaterialPurchaseCargo: "Cargo cost (₮)",
        rawMaterialPurchaseNotes: "Notes",
        rawMaterialPurchaseTotalAdded: "Total added",
        rawMaterialPurchaseTotalAmount: "Total amount",
        rawMaterialPurchaseDeleteConfirm: "Deleting this purchase will subtract the quantity from stock. Continue?",
        rawMaterialUsageTitle: "Manual usage",
        rawMaterialUsageEmpty: "No manual usage recorded.",
        rawMaterialUsageAdd: "Record usage",
        rawMaterialUsageModalTitle: "Record usage",
        rawMaterialUsedAt: "Used on",
        rawMaterialUsageQty: "Quantity",
        rawMaterialUsageReason: "Reason",
        rawMaterialUsageNotes: "Notes",
        rawMaterialUsageTotal: "Total used",
        rawMaterialUsageInsufficientStock: "Not enough stock.",
        rawMaterialUsageDeleteConfirm: "Deleting this usage entry will add the quantity back to stock. Continue?",
        rawMaterialTotalCostValue: "Total cost",
        rawMaterialTotalConsumedValue: "Total consumed",
        rawMaterialCategoryOil: "Oil",
        rawMaterialCategoryLye: "Lye",
        rawMaterialCategoryFragrance: "Fragrance",
        rawMaterialCategoryColorant: "Colorant",
        rawMaterialCategoryAdditive: "Additive",
        rawMaterialCategoryOther: "Other",
        contactsTitle: "Customer directory",
        contactsText: "Keep individual and organization customers — name, phone and address — in one register.",
        contactsListText: "Click a row to see that customer's previous purchases.",
        contactPurchaseCount: "Purchases",
        contactPurchaseTotal: "Total spent",
        contactLastPurchase: "Last purchase",
        contactAveragePurchase: "Average sale",
        contactNoPurchases: "No purchases recorded for this customer yet.",
        newContact: "New customer",
        editContact: "Edit customer",
        totalContacts: "Total customers",
        contactSearchPlaceholder: "Search by name, phone or code...",
        contactEmpty: "No customers registered yet.",
        contactNoMatch: "No customer matches this search.",
        deleteContactTitle: "Delete customer",
        deleteContactDescription: "Delete this customer? Sales already registered stay intact.",
        saleContactPicker: "Pick a registered customer",
        saleContactPickerNote: "Optional — picking one fills the fields below.",
        saleContactClear: "Clear selection",
        saleContactNoMatch: "No matching customer.",
        customersTitle: "Seller management",
        customersText: "Manage organization and individual seller records: name, phone, address, and status.",
        customerRegisteredAt: "Registered",
        customersKicker: "CRM",
        newCustomer: "New seller",
        editCustomer: "Edit seller",
        customerTypeAll: "All types",
        customerTypeOrg: "Organization",
        customerTypeInd: "Individual",
        customerCode: "Code",
        customerNameLabel: "Name",
        customerDisplayName: "Display name",
        customerRegNo: "Registration / Tax ID",
        customerContactPerson: "Contact person",
        customerPhone: "Phone",
        customerSecondaryPhone: "Secondary phone",
        customerEmail: "Email",
        customerAddress: "Address",
        customerNote: "Notes",
        customerTotalSales: "Total sales",
        customerTotalPaid: "Paid",
        customerOutstanding: "Outstanding",
        customerEmpty: "No sellers registered yet.",
        totalCustomers: "Total sellers",
        activeCustomers: "Active",
        totalOutstanding: "Total receivables",
        totalTransfers: "Total transfers",
        deleteCustomerDescription: "Delete this seller? Past transactions will remain intact.",
        transactionsTitle: "Seller ledger",
        transactionsText: "Record deliveries, sales and returns. Product stock and seller balance update automatically.",
        newTransaction: "New transaction",
        editTransaction: "Edit transaction",
        txNumber: "Number",
        txDate: "Date",
        txType: "Type",
        txTypeDelivery: "Delivery",
        txTypeSale: "Sale",
        txTypeReturn: "Return",
        txCustomer: "Seller",
        txItems: "Items",
        txAddItem: "Add item",
        txProduct: "Product",
        txVariant: "Variant",
        txQuantity: "Qty",
        txUnitPrice: "Unit price",
        txLineTotal: "Total",
        txSubtotal: "Subtotal",
        txDiscount: "Discount",
        txGrandTotal: "Grand total",
        txPaidAmount: "Paid amount",
        txPaymentMethod: "Payment method",
        txPaymentStatus: "Payment status",
        txPaymentUnpaid: "Unpaid",
        txPaymentPartial: "Partial",
        txPaymentPaid: "Paid",
        txPaymentCash: "Cash",
        txPaymentBank: "Bank",
        txPaymentQpay: "QPay",
        txPaymentOther: "Other",
        txNote: "Note",
        txEmpty: "No transactions found.",
        txTodaySales: "Today's sales",
        txMonthSales: "This month",
        txOutstanding: "Total receivables",
        txAllTypes: "All types",
        txAllCustomers: "All customers",
        deleteTransactionDescription: "Deleting this transaction will reverse stock and balance changes. Continue?",
        selectCustomerFirst: "Select a customer first.",
        addAtLeastOneItem: "Please add at least one item.",
        discountsMenu: "Discounts",
        discountsTitle: "Discount management",
        discountsText: "Set percent or fixed discounts on products with start and end dates.",
        addDiscount: "Add discount",
        discountProduct: "Product",
        discountType: "Discount type",
        discountTypePercent: "Percent (%)",
        discountTypeAmount: "Fixed amount (₮)",
        discountValue: "Discount value",
        discountStartAt: "Start date",
        discountEndAt: "End date",
        discountEmpty: "No discounts found.",
        discountModalCreate: "Add discount",
        discountModalEdit: "Edit discount",
        deleteDiscountDescription: "Delete this discount?",
        discountSavings: "Discount",
        discountOriginalPrice: "Original price",
        discountedPrice: "Discounted price",
        discountPercent: "off",
      };

}

export type AdminCopy = ReturnType<typeof getAdminCopy>;
